### ISSUE TITLE
no file 'raw_data.pkl', 'scaled_data.pkl', 'scaler.pkl'

### ISSUE THREAD

**Issue by nce3xin** [fehiepsi/web-traffic-time-series-forecasting#1]
Thanks for sharing, but when I ran mode_rnn.ipynb, in the get_data() function, there is no file 'raw_data.pkl', 'scaled_data.pkl', 'scaler.pkl' in args.intermediate_path. May I know how to obtain these files? How to generate these? Thanks a lot.

**Comment by fehiepsi** [comment]
Hi @nce3xin, you would need to set the arg 'read_from_file' from `False` to `True` in that notebook. :)

**Comment by nce3xin** [comment]
Thanks for your quick reply. :) In the case where the arg 'read_from_file' is false, I found that commenting out this sentence, this error will disappear:
intermediate_path = os.path.join(args.intermediate_path, str(args.seed))
Or we manually create a folder naming after the random number seed. :)

**Comment by fehiepsi** [comment]
Yeah, you are right! It should include some lines which check if the intermediate folder exists (if it does not exist, then creates that folder). But your solution to manually create the folder is a quick fix!
